// QuantDrill Badge Definitions Part 1 (200 badges - first half)

export const BADGES_PART_1 = [
  // ── General (7 existing badges) ──────────────────────────────────
  {
    id: 'first_drill',
    label: 'First Rep',
    description: 'Complete your first drill',
    category: 'general',
    emoji: '🎯',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ totalDrills }) => totalDrills >= 1,
  },
  {
    id: 'streak_7',
    label: '7-Day Streak',
    description: 'Train 7 consecutive days',
    category: 'general',
    emoji: '🔥',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ streak }) => streak >= 7,
  },
  {
    id: 'streak_30',
    label: 'Iron Discipline',
    description: 'Maintain a 30-day streak',
    category: 'general',
    emoji: '⚔️',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ streak }) => streak >= 30,
  },
  {
    id: 'drills_10',
    label: 'Warming Up',
    description: 'Complete 10 drills total',
    category: 'general',
    emoji: '💪',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ totalDrills }) => totalDrills >= 10,
  },
  {
    id: 'drills_100',
    label: 'Centurion',
    description: 'Complete 100 drills total',
    category: 'general',
    emoji: '💯',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ totalDrills }) => totalDrills >= 100,
  },
  {
    id: 'drills_500',
    label: 'Elite Performer',
    description: 'Complete 500 drills — top 1% territory',
    category: 'general',
    emoji: '🏆',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ totalDrills }) => totalDrills >= 500,
  },
  {
    id: 'perfect_score',
    label: 'Perfect Execution',
    description: 'Score 100/100 in any drill',
    category: 'general',
    emoji: '✨',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ maxScore }) => maxScore >= 100,
  },
  // ── Mental Math (3 existing)  ────────────────────────
  {
    id: 'speed_calculator',
    label: 'Speed Calculator',
    description: 'Score 80+ in a Mental Math drill',
    category: 'mental_math',
    emoji: '⚡',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ catBest }) => (catBest['mental_math'] ?? 0) >= 80,
  },
  {
    id: 'division_master',
    label: 'Division Master',
    description: 'Complete 10 Mental Math drills',
    category: 'mental_math',
    emoji: '➗',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ catCount }) => (catCount['mental_math'] ?? 0) >= 10,
  },
  {
    id: 'mental_elite',
    label: 'Mental Elite',
    description: 'Average 90%+ accuracy across 5 Mental Math drills',
    category: 'mental_math',
    emoji: '🧠',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ catAvgAcc, catCount }) =>
      (catCount['mental_math'] ?? 0) >= 5 && (catAvgAcc['mental_math'] ?? 0) >= 90,
  },
  // ── Percentages & Growth (3 existing) ────────────────────────────
  {
    id: 'percentage_assassin',
    label: 'Percentage Assassin',
    description: 'Score 80+ in a Percentages drill',
    category: 'percentages_growth',
    emoji: '📈',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ catBest }) => (catBest['percentages_growth'] ?? 0) >= 80,
  },
  {
    id: 'growth_analyst',
    label: 'Growth Analyst',
    description: 'Complete 10 Percentages & Growth drills',
    category: 'percentages_growth',
    emoji: '📊',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ catCount }) => (catCount['percentages_growth'] ?? 0) >= 10,
  },
  {
    id: 'compound_master',
    label: 'Compound Master',
    description: 'Score 90+ in a Percentages drill',
    category: 'percentages_growth',
    emoji: '🚀',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ catBest }) => (catBest['percentages_growth'] ?? 0) >= 90,
  },
  // ── Business Math (3 existing) ──────────────────────────────────
  {
    id: 'margin_machine',
    label: 'Margin Machine',
    description: 'Score 80+ in a Business Math drill',
    category: 'business_math',
    emoji: '💼',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ catBest }) => (catBest['business_math'] ?? 0) >= 80,
  },
  {
    id: 'profit_hunter',
    label: 'Profit Hunter',
    description: 'Complete 10 Business Math drills',
    category: 'business_math',
    emoji: '💰',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ catCount }) => (catCount['business_math'] ?? 0) >= 10,
  },
  {
    id: 'boardroom_ready',
    label: 'Boardroom Ready',
    description: 'Score 90+ in a Business Math drill',
    category: 'business_math',
    emoji: '📋',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ catBest }) => (catBest['business_math'] ?? 0) >= 90,
  },
  // ── Market Sizing (3 existing) ─────────────────────────────────
  {
    id: 'estimation_expert',
    label: 'Estimation Expert',
    description: 'Score 80+ in a Market Sizing drill',
    category: 'market_sizing',
    emoji: '🌍',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ catBest }) => (catBest['market_sizing'] ?? 0) >= 80,
  },
  {
    id: 'market_mapper',
    label: 'Market Mapper',
    description: 'Complete 10 Market Sizing drills',
    category: 'market_sizing',
    emoji: '🗺️',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ catCount }) => (catCount['market_sizing'] ?? 0) >= 10,
  },
  {
    id: 'case_cracker',
    label: 'Case Cracker',
    description: 'Score 90+ in a Market Sizing drill',
    category: 'market_sizing',
    emoji: '🔍',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ catBest }) => (catBest['market_sizing'] ?? 0) >= 90,
  },
  // ── GMAT Quant (3 existing) ────────────────────────────────────
  {
    id: 'quant_sprint',
    label: 'Quant Sprint',
    description: 'Score 80+ in a GMAT Quant drill',
    category: 'gmat_quant',
    emoji: '🎓',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ catBest }) => (catBest['gmat_quant'] ?? 0) >= 80,
  },
  {
    id: 'gmat_grinder',
    label: 'GMAT Grinder',
    description: 'Complete 10 GMAT Quant drills',
    category: 'gmat_quant',
    emoji: '📐',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ catCount }) => (catCount['gmat_quant'] ?? 0) >= 10,
  },
  {
    id: 'quant_elite',
    label: 'Quant Elite',
    description: 'Score 90+ in a GMAT Quant drill',
    category: 'gmat_quant',
    emoji: '🏅',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ catBest }) => (catBest['gmat_quant'] ?? 0) >= 90,
  },
  // ── Streak Badges (20) ───────────────────────────────────────────
  {
    id: 'streak_1',
    label: '1-Day Streak',
    description: 'Train for 1 day',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ streak }) => streak >= 1,
  },
  {
    id: 'streak_2',
    label: '2-Day Streak',
    description: 'Train for 2 consecutive days',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ streak }) => streak >= 2,
  },
  {
    id: 'streak_3',
    label: '3-Day Streak',
    description: 'Train for 3 consecutive days',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ streak }) => streak >= 3,
  },
  {
    id: 'streak_5',
    label: '5-Day Streak',
    description: 'Train for 5 consecutive days',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ streak }) => streak >= 5,
  },
  {
    id: 'streak_10',
    label: '10-Day Streak',
    description: 'Train for 10 consecutive days',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ streak }) => streak >= 10,
  },
  {
    id: 'streak_14',
    label: '14-Day Streak',
    description: 'Train for 14 consecutive days',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ streak }) => streak >= 14,
  },
  {
    id: 'streak_21',
    label: '21-Day Streak',
    description: 'Train for 21 consecutive days',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ streak }) => streak >= 21,
  },
  {
    id: 'streak_45',
    label: '45-Day Streak',
    description: 'Train for 45 consecutive days',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ streak }) => streak >= 45,
  },
  {
    id: 'streak_60',
    label: '60-Day Streak',
    description: 'Train for 60 consecutive days',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ streak }) => streak >= 60,
  },
  {
    id: 'streak_75',
    label: '75-Day Streak',
    description: 'Train for 75 consecutive days',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ streak }) => streak >= 75,
  },
  {
    id: 'streak_90',
    label: '90-Day Streak',
    description: 'Train for 90 consecutive days',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ streak }) => streak >= 90,
  },
  {
    id: 'streak_100',
    label: '100-Day Streak',
    description: 'Train for 100 consecutive days',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ streak }) => streak >= 100,
  },
  {
    id: 'streak_120',
    label: '120-Day Streak',
    description: 'Train for 120 consecutive days',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ streak }) => streak >= 120,
  },
  {
    id: 'streak_150',
    label: '150-Day Streak',
    description: 'Train for 150 consecutive days',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ streak }) => streak >= 150,
  },
  {
    id: 'streak_180',
    label: '180-Day Streak',
    description: 'Train for 180 consecutive days',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ streak }) => streak >= 180,
  },
  {
    id: 'streak_200',
    label: '200-Day Streak',
    description: 'Train for 200 consecutive days',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ streak }) => streak >= 200,
  },
  {
    id: 'streak_250',
    label: '250-Day Streak',
    description: 'Train for 250 consecutive days',
    category: 'streaks',
    emoji: '🔥',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ streak }) => streak >= 250,
  },
  {
    id: 'streak_365',
    label: '365-Day Streak',
    description: 'Train for 365 consecutive days — one full year',
    category: 'streaks',
    emoji: '👑',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ streak }) => streak >= 365,
  },
  // ── Volume Badges (20) ─────────────────────────────────────────────
  {
    id: 'volume_1',
    label: 'Getting Started',
    description: 'Complete 1 drill',
    category: 'volume',
    emoji: '🚀',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ totalDrills }) => totalDrills >= 1,
  },
  {
    id: 'volume_5',
    label: 'Off to a Start',
    description: 'Complete 5 drills',
    category: 'volume',
    emoji: '🚀',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ totalDrills }) => totalDrills >= 5,
  },
  {
    id: 'volume_25',
    label: 'Quarter Century',
    description: 'Complete 25 drills',
    category: 'volume',
    emoji: '💪',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ totalDrills }) => totalDrills >= 25,
  },
  {
    id: 'volume_75',
    label: 'Three Quarters',
    description: 'Complete 75 drills',
    category: 'volume',
    emoji: '💪',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ totalDrills }) => totalDrills >= 75,
  },
  {
    id: 'volume_150',
    label: 'Momentum Builder',
    description: 'Complete 150 drills',
    category: 'volume',
    emoji: '⚡',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ totalDrills }) => totalDrills >= 150,
  },
  {
    id: 'volume_250',
    label: 'Quarter Thousand',
    description: 'Complete 250 drills',
    category: 'volume',
    emoji: '⚡',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ totalDrills }) => totalDrills >= 250,
  },
  {
    id: 'volume_300',
    label: 'Three Hundred Club',
    description: 'Complete 300 drills',
    category: 'volume',
    emoji: '⚡',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ totalDrills }) => totalDrills >= 300,
  },
  {
    id: 'volume_400',
    label: 'Four Hundred Strong',
    description: 'Complete 400 drills',
    category: 'volume',
    emoji: '🏆',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ totalDrills }) => totalDrills >= 400,
  },
  {
    id: 'volume_600',
    label: 'Six Hundred',
    description: 'Complete 600 drills',
    category: 'volume',
    emoji: '🏆',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ totalDrills }) => totalDrills >= 600,
  },
  {
    id: 'volume_750',
    label: 'Three-Quarters Thousand',
    description: 'Complete 750 drills',
    category: 'volume',
    emoji: '🏆',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ totalDrills }) => totalDrills >= 750,
  },
  {
    id: 'volume_1000',
    label: 'Thousand Strong',
    description: 'Complete 1000 drills',
    category: 'volume',
    emoji: '👑',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ totalDrills }) => totalDrills >= 1000,
  },
  {
    id: 'volume_1500',
    label: 'One-Point-Five',
    description: 'Complete 1500 drills',
    category: 'volume',
    emoji: '👑',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ totalDrills }) => totalDrills >= 1500,
  },
  {
    id: 'volume_2000',
    label: 'Two Thousand Legend',
    description: 'Complete 2000 drills',
    category: 'volume',
    emoji: '👑',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ totalDrills }) => totalDrills >= 2000,
  },
  {
    id: 'volume_2500',
    label: 'Two-Point-Five',
    description: 'Complete 2500 drills',
    category: 'volume',
    emoji: '👑',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ totalDrills }) => totalDrills >= 2500,
  },
  {
    id: 'volume_5000',
    label: 'Five Thousand',
    description: 'Complete 5000 drills — legendary status',
    category: 'volume',
    emoji: '🌟',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ totalDrills }) => totalDrills >= 5000,
  },
];