// QuantDrill Badge Definitions Part 2 (200 badges - second half)

export const BADGES_PART_2 = [
  // ── Accuracy Badges (20) ───────────────────────────────────────────
  {
    id: 'perfect_1',
    label: 'First Perfect',
    description: 'Score 100% on 1 session',
    category: 'accuracy',
    emoji: '✨',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ perfectCount }) => (perfectCount ?? 0) >= 1,
  },
  {
    id: 'perfect_2',
    label: 'Double Perfect',
    description: 'Score 100% on 2 sessions',
    category: 'accuracy',
    emoji: '✨',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ perfectCount }) => (perfectCount ?? 0) >= 2,
  },
  {
    id: 'perfect_3',
    label: 'Triple Threat',
    description: 'Score 100% on 3 sessions',
    category: 'accuracy',
    emoji: '✨',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ perfectCount }) => (perfectCount ?? 0) >= 3,
  },
  {
    id: 'perfect_5',
    label: 'Perfect Quintet',
    description: 'Score 100% on 5 sessions',
    category: 'accuracy',
    emoji: '✨',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ perfectCount }) => (perfectCount ?? 0) >= 5,
  },
  {
    id: 'perfect_10',
    label: 'Perfection Achieved',
    description: 'Score 100% on 10 sessions',
    category: 'accuracy',
    emoji: '✨',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ perfectCount }) => (perfectCount ?? 0) >= 10,
  },
  {
    id: 'perfect_15',
    label: 'Flawless Fifteen',
    description: 'Score 100% on 15 sessions',
    category: 'accuracy',
    emoji: '✨',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ perfectCount }) => (perfectCount ?? 0) >= 15,
  },
  {
    id: 'perfect_20',
    label: 'Twenty Perfects',
    description: 'Score 100% on 20 sessions',
    category: 'accuracy',
    emoji: '✨',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ perfectCount }) => (perfectCount ?? 0) >= 20,
  },
  {
    id: 'perfect_25',
    label: 'Quarter Century Perfect',
    description: 'Score 100% on 25 sessions',
    category: 'accuracy',
    emoji: '✨',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ perfectCount }) => (perfectCount ?? 0) >= 25,
  },
  {
    id: 'perfect_30',
    label: 'Thirty Perfects',
    description: 'Score 100% on 30 sessions',
    category: 'accuracy',
    emoji: '✨',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ perfectCount }) => (perfectCount ?? 0) >= 30,
  },
  {
    id: 'perfect_40',
    label: 'Forty Perfects',
    description: 'Score 100% on 40 sessions',
    category: 'accuracy',
    emoji: '✨',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ perfectCount }) => (perfectCount ?? 0) >= 40,
  },
  {
    id: 'perfect_50',
    label: 'Fifty Perfects',
    description: 'Score 100% on 50 sessions',
    category: 'accuracy',
    emoji: '✨',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ perfectCount }) => (perfectCount ?? 0) >= 50,
  },
  {
    id: 'perfect_75',
    label: 'Seventy-Five Perfects',
    description: 'Score 100% on 75 sessions',
    category: 'accuracy',
    emoji: '✨',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ perfectCount }) => (perfectCount ?? 0) >= 75,
  },
  {
    id: 'perfect_100',
    label: 'Hundred Perfects',
    description: 'Score 100% on 100 sessions',
    category: 'accuracy',
    emoji: '✨',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ perfectCount }) => (perfectCount ?? 0) >= 100,
  },
  {
    id: 'high_accuracy_5',
    label: 'Five in a Row 80%+',
    description: 'Score 80%+ accuracy for 5 consecutive sessions',
    category: 'accuracy',
    emoji: '📈',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ highAccStreak5 }) => (highAccStreak5 ?? false),
  },
  {
    id: 'high_accuracy_10',
    label: 'Ten in a Row 80%+',
    description: 'Score 80%+ accuracy for 10 consecutive sessions',
    category: 'accuracy',
    emoji: '📈',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ highAccStreak10 }) => (highAccStreak10 ?? false),
  },
  {
    id: 'high_accuracy_20',
    label: 'Twenty in a Row 80%+',
    description: 'Score 80%+ accuracy for 20 consecutive sessions',
    category: 'accuracy',
    emoji: '📈',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ highAccStreak20 }) => (highAccStreak20 ?? false),
  },
  {
    id: 'high_accuracy_30',
    label: 'Thirty in a Row 80%+',
    description: 'Score 80%+ accuracy for 30 consecutive sessions',
    category: 'accuracy',
    emoji: '📈',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ highAccStreak30 }) => (highAccStreak30 ?? false),
  },
  {
    id: 'high_accuracy_50',
    label: 'Fifty in a Row 80%+',
    description: 'Score 80%+ accuracy for 50 consecutive sessions',
    category: 'accuracy',
    emoji: '📈',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ highAccStreak50 }) => (highAccStreak50 ?? false),
  },

  // ── Speed Badges (20) ──────────────────────────────────────────────
  {
    id: 'speed_10s_1',
    label: 'Quick',
    description: 'Average response under 10 seconds for 1 session',
    category: 'speed',
    emoji: '⚡',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ speedSub10_1 }) => (speedSub10_1 ?? false),
  },
  {
    id: 'speed_9s_1',
    label: 'Rapid',
    description: 'Average response under 9 seconds for 1 session',
    category: 'speed',
    emoji: '⚡',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ speedSub9_1 }) => (speedSub9_1 ?? false),
  },
  {
    id: 'speed_8s_1',
    label: 'Lightning',
    description: 'Average response under 8 seconds for 1 session',
    category: 'speed',
    emoji: '⚡',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ speedSub8_1 }) => (speedSub8_1 ?? false),
  },
  {
    id: 'speed_7s_1',
    label: 'Blazing',
    description: 'Average response under 7 seconds for 1 session',
    category: 'speed',
    emoji: '⚡',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ speedSub7_1 }) => (speedSub7_1 ?? false),
  },
  {
    id: 'speed_6s_1',
    label: 'Supersonic',
    description: 'Average response under 6 seconds for 1 session',
    category: 'speed',
    emoji: '⚡',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ speedSub6_1 }) => (speedSub6_1 ?? false),
  },
  {
    id: 'speed_5s_1',
    label: 'Warp Speed',
    description: 'Average response under 5 seconds for 1 session',
    category: 'speed',
    emoji: '⚡',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ speedSub5_1 }) => (speedSub5_1 ?? false),
  },
  {
    id: 'speed_8s_5',
    label: 'Consistent Speed',
    description: 'Average response under 8 seconds for 5 consecutive sessions',
    category: 'speed',
    emoji: '⚡',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ speedSub8_5 }) => (speedSub8_5 ?? false),
  },
  {
    id: 'speed_8s_10',
    label: 'Speed Champion',
    description: 'Average response under 8 seconds for 10 consecutive sessions',
    category: 'speed',
    emoji: '⚡',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ speedSub8_10 }) => (speedSub8_10 ?? false),
  },
  {
    id: 'speed_8s_20',
    label: 'Speed Master',
    description: 'Average response under 8 seconds for 20 consecutive sessions',
    category: 'speed',
    emoji: '⚡',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ speedSub8_20 }) => (speedSub8_20 ?? false),
  },
  {
    id: 'speed_7s_5',
    label: 'Seven Second Pro',
    description: 'Average response under 7 seconds for 5 consecutive sessions',
    category: 'speed',
    emoji: '⚡',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ speedSub7_5 }) => (speedSub7_5 ?? false),
  },
  {
    id: 'speed_7s_10',
    label: 'Seven Second Streak',
    description: 'Average response under 7 seconds for 10 consecutive sessions',
    category: 'speed',
    emoji: '⚡',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ speedSub7_10 }) => (speedSub7_10 ?? false),
  },
  {
    id: 'speed_6s_5',
    label: 'Six Second Savant',
    description: 'Average response under 6 seconds for 5 consecutive sessions',
    category: 'speed',
    emoji: '⚡',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ speedSub6_5 }) => (speedSub6_5 ?? false),
  },
  {
    id: 'speed_6s_10',
    label: 'Six Second Elite',
    description: 'Average response under 6 seconds for 10 consecutive sessions',
    category: 'speed',
    emoji: '⚡',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ speedSub6_10 }) => (speedSub6_10 ?? false),
  },
  {
    id: 'speed_5s_5',
    label: 'Five Second Master',
    description: 'Average response under 5 seconds for 5 consecutive sessions',
    category: 'speed',
    emoji: '⚡',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ speedSub5_5 }) => (speedSub5_5 ?? false),
  },
  {
    id: 'speed_5s_10',
    label: 'Five Second Legend',
    description: 'Average response under 5 seconds for 10 consecutive sessions',
    category: 'speed',
    emoji: '⚡',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ speedSub5_10 }) => (speedSub5_10 ?? false),
  },

  // ── Category Mastery Badges (25) ───────────────────────────────────
  {
    id: 'mental_10',
    label: 'Mental Math Novice',
    description: 'Complete 10 Mental Math drills',
    category: 'mastery',
    emoji: '⚡',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ catCount }) => (catCount['mental_math'] ?? 0) >= 10,
  },
  {
    id: 'mental_25',
    label: 'Mental Math Enthusiast',
    description: 'Complete 25 Mental Math drills',
    category: 'mastery',
    emoji: '⚡',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ catCount }) => (catCount['mental_math'] ?? 0) >= 25,
  },
  {
    id: 'mental_50',
    label: 'Mental Math Adept',
    description: 'Complete 50 Mental Math drills',
    category: 'mastery',
    emoji: '⚡',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ catCount }) => (catCount['mental_math'] ?? 0) >= 50,
  },
  {
    id: 'mental_100',
    label: 'Mental Math Master',
    description: 'Complete 100 Mental Math drills',
    category: 'mastery',
    emoji: '⚡',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ catCount }) => (catCount['mental_math'] ?? 0) >= 100,
  },
  {
    id: 'mental_200',
    label: 'Mental Math Legend',
    description: 'Complete 200 Mental Math drills',
    category: 'mastery',
    emoji: '⚡',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ catCount }) => (catCount['mental_math'] ?? 0) >= 200,
  },
  {
    id: 'percentages_10',
    label: 'Percentages Novice',
    description: 'Complete 10 Percentages drills',
    category: 'mastery',
    emoji: '📈',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ catCount }) => (catCount['percentages_growth'] ?? 0) >= 10,
  },
  {
    id: 'percentages_25',
    label: 'Percentages Enthusiast',
    description: 'Complete 25 Percentages drills',
    category: 'mastery',
    emoji: '📈',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/30',
    check: ({ catCount }) => (catCount['percentages_growth'] ?? 0) >= 25,
  },
  {
    id: 'percentages_50',
    label: 'Percentages Adept',
    description: 'Complete 50 Percentages drills',
    category: 'mastery',
    emoji: '📈',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ catCount }) => (catCount['percentages_growth'] ?? 0) >= 50,
  },
  {
    id: 'percentages_100',
    label: 'Percentages Master',
    description: 'Complete 100 Percentages drills',
    category: 'mastery',
    emoji: '📈',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ catCount }) => (catCount['percentages_growth'] ?? 0) >= 100,
  },
  {
    id: 'percentages_200',
    label: 'Percentages Legend',
    description: 'Complete 200 Percentages drills',
    category: 'mastery',
    emoji: '📈',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ catCount }) => (catCount['percentages_growth'] ?? 0) >= 200,
  },
  {
    id: 'business_10',
    label: 'Business Math Novice',
    description: 'Complete 10 Business Math drills',
    category: 'mastery',
    emoji: '💼',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ catCount }) => (catCount['business_math'] ?? 0) >= 10,
  },
  {
    id: 'business_25',
    label: 'Business Math Enthusiast',
    description: 'Complete 25 Business Math drills',
    category: 'mastery',
    emoji: '💼',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ catCount }) => (catCount['business_math'] ?? 0) >= 25,
  },
  {
    id: 'business_50',
    label: 'Business Math Adept',
    description: 'Complete 50 Business Math drills',
    category: 'mastery',
    emoji: '💼',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ catCount }) => (catCount['business_math'] ?? 0) >= 50,
  },
  {
    id: 'business_100',
    label: 'Business Math Master',
    description: 'Complete 100 Business Math drills',
    category: 'mastery',
    emoji: '💼',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ catCount }) => (catCount['business_math'] ?? 0) >= 100,
  },
  {
    id: 'business_200',
    label: 'Business Math Legend',
    description: 'Complete 200 Business Math drills',
    category: 'mastery',
    emoji: '💼',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ catCount }) => (catCount['business_math'] ?? 0) >= 200,
  },
  {
    id: 'gmat_10',
    label: 'GMAT Novice',
    description: 'Complete 10 GMAT/GRE Quant drills',
    category: 'mastery',
    emoji: '📐',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ catCount }) => (catCount['gmat_quant'] ?? 0) >= 10,
  },
  {
    id: 'gmat_25',
    label: 'GMAT Enthusiast',
    description: 'Complete 25 GMAT/GRE Quant drills',
    category: 'mastery',
    emoji: '📐',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ catCount }) => (catCount['gmat_quant'] ?? 0) >= 25,
  },
  {
    id: 'gmat_50',
    label: 'GMAT Adept',
    description: 'Complete 50 GMAT/GRE Quant drills',
    category: 'mastery',
    emoji: '📐',
    color: 'text-neon-orange',
    bg: 'bg-orange-500/10',
    border: 'border-orange-500/30',
    check: ({ catCount }) => (catCount['gmat_quant'] ?? 0) >= 50,
  },
  {
    id: 'gmat_100',
    label: 'GMAT Master',
    description: 'Complete 100 GMAT/GRE Quant drills',
    category: 'mastery',
    emoji: '📐',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ catCount }) => (catCount['gmat_quant'] ?? 0) >= 100,
  },
  {
    id: 'gmat_200',
    label: 'GMAT Legend',
    description: 'Complete 200 GMAT/GRE Quant drills',
    category: 'mastery',
    emoji: '📐',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ catCount }) => (catCount['gmat_quant'] ?? 0) >= 200,
  },
  {
    id: 'market_10',
    label: 'Market Sizing Novice',
    description: 'Complete 10 Market Sizing drills',
    category: 'mastery',
    emoji: '🌍',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ catCount }) => (catCount['market_sizing'] ?? 0) >= 10,
  },
  {
    id: 'market_25',
    label: 'Market Sizing Enthusiast',
    description: 'Complete 25 Market Sizing drills',
    category: 'mastery',
    emoji: '🌍',
    color: 'text-neon-purple',
    bg: 'bg-primary/10',
    border: 'border-primary/30',
    check: ({ catCount }) => (catCount['market_sizing'] ?? 0) >= 25,
  },
  {
    id: 'market_50',
    label: 'Market Sizing Adept',
    description: 'Complete 50 Market Sizing drills',
    category: 'mastery',
    emoji: '🌍',
    color: 'text-neon-cyan',
    bg: 'bg-neon-cyan/10',
    border: 'border-neon-cyan/30',
    check: ({ catCount }) => (catCount['market_sizing'] ?? 0) >= 50,
  },
  {
    id: 'market_100',
    label: 'Market Sizing Master',
    description: 'Complete 100 Market Sizing drills',
    category: 'mastery',
    emoji: '🌍',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ catCount }) => (catCount['market_sizing'] ?? 0) >= 100,
  },
  {
    id: 'market_200',
    label: 'Market Sizing Legend',
    description: 'Complete 200 Market Sizing drills',
    category: 'mastery',
    emoji: '🌍',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/30',
    check: ({ catCount }) => (catCount['market_sizing'] ?? 0) >= 200,
  },
];